# Generated by Django 4.1.3 on 2022-11-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_trailer_screening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hall',
            old_name='tickets',
            new_name='seats',
        ),
    ]
