# Generated by Django 4.1.3 on 2022-11-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_tickets_hall_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
