# Generated by Django 4.1.3 on 2022-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_cast_movie_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.SmallIntegerField(),
        ),
    ]
