# Generated by Django 4.1.3 on 2022-12-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screening',
            old_name='hours_of_screening',
            new_name='screening_time',
        ),
        migrations.RemoveField(
            model_name='screening',
            name='dates_of_screening',
        ),
    ]
