# Generated by Django 4.1.4 on 2022-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='tickets_left',
            field=models.SmallIntegerField(default=0),
        ),
    ]
